# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65\x63ho_service.proto\x12\x0c\x65\x63ho_service\"\x1c\n\x0b\x45\x63hoRequest\x12\r\n\x05value\x18\x01 \x01(\t\"\x1d\n\x0c\x45\x63hoResponse\x12\r\n\x05value\x18\x01 \x01(\t2N\n\x0b\x45\x63hoService\x12?\n\x04\x45\x63ho\x12\x19.echo_service.EchoRequest\x1a\x1a.echo_service.EchoResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ECHOREQUEST']._serialized_start=36
  _globals['_ECHOREQUEST']._serialized_end=64
  _globals['_ECHORESPONSE']._serialized_start=66
  _globals['_ECHORESPONSE']._serialized_end=95
  _globals['_ECHOSERVICE']._serialized_start=97
  _globals['_ECHOSERVICE']._serialized_end=175
# @@protoc_insertion_point(module_scope)
